### ISSUE TITLE
Invalid module path

### ISSUE THREAD

**Issue by AlekSi** [dmgk/faker#8]
```
-> vgo get -v syreclabs.com/go/faker/v2
Fetching https://syreclabs.com/go/faker/v2?go-get=1
Parsing meta tags from https://syreclabs.com/go/faker/v2?go-get=1 (status code 200)
get "syreclabs.com/go/faker/v2": found meta tag get.metaImport{Prefix:"syreclabs.com/go/faker", VCS:"git", RepoRoot:"https://syreclabs.com/go/faker.git"} at https://syreclabs.com/go/faker/v2?go-get=1
get "syreclabs.com/go/faker/v2": verifying non-authoritative meta tag
Fetching https://syreclabs.com/go/faker?go-get=1
Parsing meta tags from https://syreclabs.com/go/faker?go-get=1 (status code 200)
go: syreclabs.com/go/faker/v2@v2.0.1: go.mod has non-.../v2 module path "syreclabs.com/go/faker" (and .../v2/go.mod does not exist) at revision v2.0.1
go: error loading module requirements
```

https://github.com/dmgk/faker/blob/master/go.mod should contain
```
module "syreclabs.com/go/faker/v2"
```

More info: https://github.com/golang/go/wiki/Modules#new-concepts

**Comment by dmgk** [comment]
Thanks for reporting this.

Adding v2 tag turned out to be a mistake, I didn't realize that vgo handles versions v2 and later differently and requires an import suffix both in go.mod and in import paths.

As I have a bunch of projects that use faker for tests and I don't have an intention of updating faker import paths in all of them, the easiest solution is (unfortunately) to just delete v2 tags and go back to v1.

Sorry for the confusion.
